const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomUUID, randomBytes } = require('node:crypto');
const { Pool } = require('pg');
const { migrate } = require('../server/db');

test('V0.1 records survive V0.2 migration with stable recipient order', async (t) => {
  const connectionString = process.env.DATABASE_URL || 'postgresql://giftbook@127.0.0.1:55437/giftbook';
  const admin = new Pool({ connectionString });
  const schema = 'test_migration_' + randomBytes(8).toString('hex');
  await admin.query('CREATE SCHEMA ' + schema);
  const pool = new Pool({ connectionString, options: '-c search_path=' + schema });
  t.after(async () => {
    await pool.end();
    await admin.query('DROP SCHEMA ' + schema + ' CASCADE');
    await admin.end();
  });
  await pool.query(await fs.readFile(path.join(__dirname, '../migrations/001_v01.sql'), 'utf8'));
  const userId = randomUUID(), olderId = randomUUID(), newerId = randomUUID(), giftId = randomUUID();
  await pool.query('INSERT INTO users(id) VALUES($1)', [userId]);
  await pool.query("INSERT INTO recipients(id,user_id,display_name,relation_type,created_at) VALUES($1,$3,'Rose','恋人','2025-01-01'),($2,$3,'妈妈','家人','2026-01-01')", [olderId, newerId, userId]);
  await pool.query("INSERT INTO gift_records(id,user_id,recipient_id,request_id,request_hash,gift_name,reaction_level,gifted_at) VALUES($1,$2,$3,$4,'test','拍立得',4,'2025-09-12')", [giftId, userId, olderId, randomUUID()]);
  await pool.query(await fs.readFile(path.join(__dirname, '../migrations/002_v011.sql'), 'utf8'));
  await pool.query(await fs.readFile(path.join(__dirname, '../migrations/003_v02.sql'), 'utf8'));
  const caseId = randomUUID();
  await pool.query("INSERT INTO public_cases(id,owner_id,source_gift_id,gift_name,relation_type,age_range,occasion,price_range,wanted_level,reaction_level,behavior,experience,status) VALUES($1,$2,$3,'拍立得','恋人','26–30','生日','500–1000','没提过',4,'当天就用了，后来分享朋友圈','旧经验','published')", [caseId,userId,giftId]);
  const negativeCaseId = randomUUID();
  await pool.query("INSERT INTO public_cases(id,owner_id,gift_name,relation_type,age_range,occasion,price_range,wanted_level,reaction_level,behavior,experience,status) VALUES($1,$2,'旧记录','恋人','26–30','生日','1500+','没提过',2,'当天没用，也没有分享朋友圈','','removed')", [negativeCaseId,userId]);
  const ambiguousCaseId = randomUUID();
  await pool.query("INSERT INTO public_cases(id,owner_id,gift_name,relation_type,age_range,occasion,price_range,wanted_level,reaction_level,behavior,experience,status) VALUES($1,$2,'旧记录二','恋人','26–30','生日','0–100','没提过',2,'当天忘了用，一直闲置','','removed')", [ambiguousCaseId,userId]);
  const beforeCount = Number((await pool.query('SELECT count(*) FROM public_cases')).rows[0].count);
  await migrate(pool);
  const migrated = (await pool.query('SELECT behavior_legacy,behavior_evidence,price_range,legacy_price_range,source_type FROM public_cases WHERE id=$1', [caseId])).rows[0];
  assert.equal(Number((await pool.query('SELECT count(*) FROM public_cases')).rows[0].count), beforeCount);
  assert.equal(migrated.behavior_legacy, '当天就用了，后来分享朋友圈');
  assert.deepEqual(migrated.behavior_evidence, ['used_immediately', 'shared_with_others']);
  assert.equal(migrated.price_range, '500–1000');
  assert.equal(migrated.legacy_price_range, '500–1000');
  assert.equal(migrated.source_type, 'user_generated');
  assert.deepEqual((await pool.query('SELECT behavior_evidence,legacy_price_range FROM public_cases WHERE id=$1', [negativeCaseId])).rows[0], { behavior_evidence: ['legacy_observed'], legacy_price_range: '1500+' });
  assert.deepEqual((await pool.query('SELECT behavior_evidence,legacy_price_range FROM public_cases WHERE id=$1', [ambiguousCaseId])).rows[0], { behavior_evidence: ['legacy_observed'], legacy_price_range: '0–100' });
  await assert.rejects(pool.query("UPDATE public_cases SET behavior_evidence=ARRAY['used_immediately','used_immediately'] WHERE id=$1", [caseId]), /public_cases_evidence_valid/);
  await assert.rejects(pool.query("UPDATE public_cases SET behavior_legacy=NULL,behavior_evidence=ARRAY['legacy_observed'] WHERE id=$1", [caseId]), /public_cases_evidence_valid/);
  assert.deepEqual((await pool.query('SELECT id FROM recipients WHERE user_id=$1 ORDER BY sort_order', [userId])).rows.map((row) => row.id), [newerId, olderId]);
  assert.equal((await pool.query('SELECT gift_name FROM gift_records WHERE id=$1', [giftId])).rows[0].gift_name, '拍立得');
  assert.equal((await pool.query("SELECT to_regclass('public_cases') AS cases,to_regclass('case_helpful') AS helpful")).rows[0].cases, 'public_cases');
  await pool.query('UPDATE recipients SET sort_order=0 WHERE id=$1', [olderId]);
  await pool.query("UPDATE public_cases SET price_range='1500+',legacy_price_range=NULL WHERE id=$1", [caseId]);
  await migrate(pool);
  assert.equal((await pool.query('SELECT sort_order FROM recipients WHERE id=$1', [olderId])).rows[0].sort_order, 0);
  assert.equal(Number((await pool.query('SELECT count(*) FROM public_cases')).rows[0].count), beforeCount);
  assert.equal((await pool.query('SELECT legacy_price_range FROM public_cases WHERE id=$1', [caseId])).rows[0].legacy_price_range, null);
});
